LRDOCS-10554 + LRDOCS-10354 + LRDOCS-9624 Navigation Menu types
Alec-Shay/liferay-learn pull request #117
Opened 2022-06-02 22:12 UTC by Alec-Shay

See: https://issues.liferay.com/browse/LRDOCS-9624
https://issues.liferay.com/browse/LRDOCS-10354
https://issues.liferay.com/browse/LRDOCS-10554

This adds a new reference article giving an overview of the different Navigation Menu types. (Note that there is at least one type, the `Object` type, that is still being handled on a separate ticket, so it is not included here)

This covers multiple tickets because all of these tickets involve the addition or improvements to this feature, and they should all be covered by these changes. Also related: https://issues.liferay.com/browse/LRDOCS-10229

2022-06-03 10:50 UTC, lfbesada requested changes
Hi @Alec-Shay 
Thank you so much for your work! It is clearer and understandable 👏  
I have put some notes for details that are not entirely accurate.
Thank you very much ❤️

2022-06-03 10:50 UTC, lfbesada commented on docs/dxp/latest/en/site-building/site-navigation/navigation-menu-element-types.md
> +If a submenu has no other elements organized under it, then it does not appear in the Navigation Menu for Users.
That is not exact, it depends on the template that displays the menu. Some OOTB Navigation Menu's ADTs don't display the item if it doesn't have a URL and it doesn't have children, but others do it. For example, "Bar bundles styled" that is the default ADT doesn't display it but "List Menu" does.

2022-06-03 10:50 UTC, lfbesada commented on docs/dxp/latest/en/site-building/site-navigation/navigation-menu-element-types.md
> +Navigation Menus have a variety of types of elements that you can add and arrange in your desired hierarchy with their own links. These types include [specific pages](#pages), Display Pages for speci
Vocabulary is not a Display Page type, so maybe it could be mentioned here as another element type

2022-06-03 10:50 UTC, lfbesada commented on docs/dxp/latest/en/site-building/site-navigation/navigation-menu-element-types.md
> +You can add a [blog entry](../../content-authoring-and-management/blogs/adding-blog-entries.md) as an independent menu element that links to the entry's [Display Page](../displaying-content/using-dis
As in the submenu case if it doesn't have a link could be hidden from the navigation or not, depending on the ADT used to display the menu.

2022-06-03 10:50 UTC, lfbesada commented on docs/dxp/latest/en/site-building/site-navigation/navigation-menu-element-types.md
> +You can add a [web content article](../../content-authoring-and-management/web-content/web-content-articles/adding-a-basic-web-content-article.md) as an independent menu element that links to the art
Same as above

2022-06-03 10:50 UTC, lfbesada commented on docs/dxp/latest/en/site-building/site-navigation/navigation-menu-element-types.md
> +You can add a [document](../../content-authoring-and-management/documents-and-media/documents-and-media-overview.md) as an independent menu element that links to the document's [Display Page](../disp
Same as above

2022-06-03 10:50 UTC, lfbesada commented on docs/dxp/latest/en/site-building/site-navigation/navigation-menu-element-types.md
> +You can add a [Category](../../content-authoring-and-management/tags-and-categories/defining-categories-and-vocabularies-for-content.md#defining-categories) as a menu element that links to the Catego
Same as above

2022-06-03 10:50 UTC, lfbesada commented on docs/dxp/latest/en/site-building/site-navigation/navigation-menu-element-types.md
> +From Liferay 7.4 versions U9+ and GA13+, adding a Category also adds all of its Subcategories with their current hierarchy.
That is not correct, the Category item is not dynamic just Vocabulary item type is a dynamic one. A Category item only represents that category and its behavior is the same way as the other types associated with Display Page: web contents, blogs, documents, etc. The only differences in the case of Category item are:
1. When adding a new item of Category type, multi-selection is enabled. It allow adding multiple elements at once, adding them with a hierarchy equal to the one seen in the selector. The other types associated with Display Page, have no possibility of multi-selection, have to be created one by one.
2. In the contextual edition menu, the Category item has extra information fields to inform about their site and its vocabulary

2022-06-03 10:50 UTC, lfbesada commented on docs/dxp/latest/en/site-building/site-navigation/navigation-menu-element-types.md
> +If a Category added as a Navigation Menu element contains Subcategories, changes to the Subcategories do not automatically reflect in the Navigation Menu's hierarchy. If you want changes to the Subca
Subcategories are other independent menu items just like parent categories.

2022-06-03 10:50 UTC, lfbesada commented on docs/dxp/latest/en/site-building/site-navigation/navigation-menu-element-types.md
> +Each top-level Category in the Vocabulary must have a configured Display Page for it to appear in the Navigation Menu. Categories shown in the menu still display all Subcategories, with or without th
Same as above, elements that don't have a link could be hidden from the navigation or not, depending on the ADT used to display the menu.

2022-06-06 23:21 UTC, Alec-Shay commented
Thank you for the feedback, @lfbesada! Glad you caught that the presentation depends on the Application Display Template, I didn't consider that (and also that I was wrong about Subcategories automatically being included when adding Categories). I'm making the edits as per your suggestions before I push this forward. Thanks!

2022-06-07 17:12 UTC, closed without merging